services:
  api:
    image: ghcr.io/intellijb/horizon-fastify:latest
    container_name: horizon_fastify
    restart: unless-stopped
    env_file: .env.production
    # 앱이 어떤 키를 참조하든 Redis/PG를 무조건 내부 컨테이너로 보게 강제 주입
    environment:
      # PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER:-horizon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-horizon}
      POSTGRES_URI: ${POSTGRES_URI:-postgresql://horizon:${POSTGRES_PASSWORD}@postgres:5432/horizon}
      DATABASE_URL: ${DATABASE_URL:-postgresql://horizon:${POSTGRES_PASSWORD}@postgres:5432/horizon}

      # Redis (모든 경우 커버)
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URI: ${REDIS_URI:-redis://:${REDIS_PASSWORD}@redis:6379/0}
      REDIS_URL: ${REDIS_URL:-redis://:${REDIS_PASSWORD}@redis:6379/0}
      REDIS_HOST: redis
      REDIS_PORT: "6379"

      # Fastify 기본 바인딩
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-3000}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    # 호스트 20000 → 컨테이너 3000 (rabbit과 충돌 회피)
    ports:
      - "${API_PORT:-20000}:3000"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks: [horizon_network]

  postgres:
    image: postgres:17.5-alpine
    container_name: horizon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-horizon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-horizon}
    # 외부에서 접속 필요 시 20432 노출
    ports:
      - "${POSTGRES_PORT:-20432}:5432"
    volumes:
      - horizon_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-horizon} -d ${POSTGRES_DB:-horizon}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks: [horizon_network]

  redis:
    image: redis:7.2-alpine
    container_name: horizon_redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--save",
        "60",
        "1",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]
    # 외부에서 접속 필요 시 20379 노출
    ports:
      - "${REDIS_PORT:-20379}:6379"
    volumes:
      - horizon_redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} PING | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks: [horizon_network]

networks:
  horizon_network:
    name: horizon_network
    driver: bridge

volumes:
  horizon_postgres_data:
    name: horizon_postgres_data
  horizon_redis_data:
    name: horizon_redis_data
