name: ci-cd
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push image (horizon-fastify)
        working-directory: ./horizon-fastify
        run: |
          IMAGE=ghcr.io/intellijb/horizon-fastify:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy locally (compose in /home/jb/horizon-fastify)
        working-directory: /home/jb/horizon-fastify
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker compose -f docker-compose.production.yaml --env-file .env.production pull
          docker compose -f docker-compose.production.yaml --env-file .env.production up -d
          docker compose -f docker-compose.production.yaml --env-file .env.production ps
